apiVersion : apps/v1
kind: Deployment
metadata:
  name: "test-2ca0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "test-2ca0"
  template:
    metadata:
      labels:
        app: "test-2ca0"
    spec:
      containers:
        - name: "test-2ca0"
          image: "mouimetregistry.azurecr.io/test"
          ports:
          - containerPort: 80